-- Create ENUM types for activity logs
CREATE TYPE "activity_action_type" AS ENUM (
  'create',
  'update',
  'delete',
  'login',
  'logout'
);

CREATE TYPE "activity_module_type" AS ENUM (
  'user',
  'post',
  'category',
  'tags',
  'testimoni',
  'members',
  'teams',
  'dokumen',
  'settings',
  'auth'
);

-- Create activity_logs table
CREATE TABLE "activity_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL,
  "action_type" activity_action_type NOT NULL,
  "module" activity_module_type NOT NULL,
  "description" TEXT,
  "target_id" INT,
  "old_value" JSONB,
  "new_value" JSONB,
  "ip_address" VARCHAR(45),
  "user_agent" TEXT,
  "created_at" TIMESTAMP DEFAULT (now())
);

-- Add Foreign Key
ALTER TABLE "activity_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

-- Create Indexes
CREATE INDEX ON "activity_logs" ("user_id");
CREATE INDEX ON "activity_logs" ("module");
CREATE INDEX ON "activity_logs" ("action_type");
CREATE INDEX ON "activity_logs" ("created_at");
