CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "category_id" int NOT NULL,
  "title" varchar(255) NOT NULL,
  "slug" varchar(255) UNIQUE NOT NULL,
  "excerpt" text,
  "content" text NOT NULL,
  "featured_image" varchar(255),
  "status" post_status NOT NULL DEFAULT 'draft',
  "published_at" timestamp,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE INDEX ON "posts" ("user_id");
CREATE INDEX ON "posts" ("category_id");
CREATE INDEX ON "posts" ("status");
CREATE UNIQUE INDEX ON "posts" ("slug");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "posts" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");
