-- Create document_type enum
CREATE TYPE document_type AS ENUM (
  'produk_hukum',
  'lagu_organisasi',
  'logo_organisasi'
);

-- Create documents table
CREATE TABLE IF NOT EXISTS "documents" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "file_type" document_type NOT NULL,
  "file_uri" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

-- Create index for soft delete and file_type queries
CREATE INDEX idx_documents_deleted_at ON documents(deleted_at);
CREATE INDEX idx_documents_file_type ON documents(file_type);
