CREATE TABLE "members" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(100) NOT NULL,
  "position" varchar(100) NOT NULL,
  "photo_uri" varchar(255),
  "social_links" jsonb,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);
