CREATE TABLE "visitors" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ip_address" varchar(50) NOT NULL,
  "platform" varchar(255),
  "visited_at" timestamp DEFAULT (now())
);

-- Index untuk optimasi query: cek IP + tanggal
CREATE INDEX idx_visitors_ip_date ON "visitors" ("ip_address", DATE("visited_at"));

-- Index untuk query statistik berdasarkan tanggal
CREATE INDEX idx_visitors_visited_at ON "visitors" ("visited_at");
