-- Alter site_settings table to match new design
-- Remove old columns
ALTER TABLE "site_settings" DROP COLUMN IF EXISTS "logo_footer";
ALTER TABLE "site_settings" DROP COLUMN IF EXISTS "social_links";
ALTER TABLE "site_settings" DROP COLUMN IF EXISTS "contact_info";

-- Add new columns
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "site_title" varchar(100);
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "logo_big" varchar(255);
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "facebook_url" varchar(255);
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "twitter_url" varchar(255);
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "linkedin_url" varchar(255);
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "instagram_url" varchar(255);
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "youtube_url" varchar(255);
ALTER TABLE "site_settings" ADD COLUMN IF NOT EXISTS "github_url" varchar(255);

-- Create contacts table (singleton like about)
CREATE TABLE IF NOT EXISTS "contacts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address" text,
  "email" varchar(100),
  "phone" varchar(50),
  "google_maps_url" varchar(500),
  "updated_at" timestamp DEFAULT (now())
);

-- Insert default empty record for contacts (singleton)
INSERT INTO "contacts" (id) VALUES (1) ON CONFLICT DO NOTHING;
