CREATE TABLE "post_views" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "ip_address" varchar(45),
  "user_agent" text,
  "viewed_at" timestamp DEFAULT (now())
);

CREATE INDEX ON "post_views" ("post_id");
CREATE INDEX ON "post_views" ("post_id", "ip_address");
CREATE INDEX ON "post_views" ("viewed_at");

ALTER TABLE "post_views" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
