CREATE TABLE "about" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "history" text,
  "vision" text,
  "mission" text,
  "image_uri" varchar(255),
  "video_url" varchar(255),
  "updated_at" timestamp DEFAULT (now())
);
