CREATE TABLE "site_settings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "site_name" varchar(100),
  "site_description" text,
  "logo_header" varchar(255),
  "logo_footer" varchar(255),
  "favicon" varchar(255),
  "social_links" jsonb,
  "contact_info" jsonb,
  "updated_at" timestamp DEFAULT (now())
);
