CREATE TABLE "testimonials" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "organization" varchar(100),
  "position" varchar(100),
  "content" text NOT NULL,
  "photo_uri" varchar(255),
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);
