CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" int NOT NULL,
  "parent_id" int,
  "user_id" int,
  "guest_name" varchar(100),
  "guest_email" varchar(100),
  "content" text NOT NULL,
  "status" comment_status DEFAULT 'pending',
  "created_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

ALTER TABLE "comments" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("parent_id") REFERENCES "comments" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
