CREATE TABLE "subscribers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(100) UNIQUE NOT NULL,
  "status" subscriber_status DEFAULT 'active',
  "verification_token" varchar(64),
  "verified_at" timestamp,
  "created_at" timestamp DEFAULT (now())
);
